apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mysql-rs

spec:
  replicas: 1 
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: mysql-pod
      labels:
        env: dev
    spec:
      containers: 
       - name: mysql-con
         image: "mysql:5.6"
         env: 
          - name: MYSQL_ROOT_PASSWORD
            value: redhat
          - name: MYSQL_DATABASE
            value: mylwbd
     
     