apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
spec:
  replicas: 3
  selector:
    env: production
  template:
    metadata:
      name: web-pod
      labels:
        env: production
    spec:
      containers:
        - name: web-con
          image: httpd
   